### PR TITLE
QuickSqliteRenderer

### PR DESCRIPTION
**Pull request by Sebastienbr**
@ikelos
As discussed in https://github.com/volatilityfoundation/volatility/issues/205, here's the QuickSqliteRenderer. Thanks!

### CODE REVIEW

**Comment by ikelos** [comment]
Ah, ok, so it is just using the executemany function to speed things up.  There's a fair bit of duplication going on (is it slower to always build up the accumulator and use executemany no matter the number of rows?), and the limit seems a little arbitrary.

It's also not clear how/whether this copes properly with tree structures?  It seems like you're keeping the id value, but then not using it for the parent value at all (that seems hard coded to 0).  So lastly I'm a little worried about memory consumption.  I think perhaps something that batches the inserts up with a limit (such as 20,000 entries per write) might work quite well (limiting the memory but allowing big speed-ups on chunks).

I can have a go at reworking this in a few days, or I'm happy for you to fix it up yourself?  Please ignore or delete the __author__ line (pycharm puts it in automatically), the correct location for attribution is in the CREDITS.txt file in the root of the volatility project (otherwise all the source files get littered with names).  5:)  Thanks!

**Comment by Sebastienbr** [comment]
Thanks Mike for your comments!

**_is it slower to always build up the accumulator and use executemany no matter the number of rows?_**

Here's a quick benchmark I have done on my computer. Vadinfo plugin was use for this test (my test memory dump insert 4820 nodes). Results is the time it takes to run the plugin:

   - T1- vadinfo with sqlite render: 5 min., 2 sec.
   - T2- vadinfo with quicksqlite render and executemany: 1 min., 5 sec.
   - T3- vadinfo, quicksqlite render without executemany (see below for the test code): 1 min., 42 sec. 

It seems faster to run the executemany function no matter the number of rows.

Quicksqlite test code used for T3:

```
        def _add_row(node, accumulator):
            accumulator = accumulator + 1
            self._db.execute("BEGIN TRANSACTION")			
            insert = "INSERT INTO " + self._plugin_name + " VALUES (?, ?, " + ", ".join(["?"] * len(node.values)) + ")"
            self._db.execute(insert, [accumulator, 0] + [str(v) for v in node.values])
            self._db.execute("COMMIT TRANSACTION")
            return accumulator         

        grid.populate(_add_row, 0)
```


**_limit seems a little arbitrary_**

In this benchmark, I run memmap (with more than a million nodes) and I monitor the WMI's Working Set Peak (i.e: memory consumption) of the python process. VM snapshot is restore between every test to avoid a cache effect. 

|Quicksqlite limit   	|Memory consumption   	|Time to run the plugin   	|
|---	|---	|---	|
|1 000 limit   	|748 716 032 bytes   	|  4 min. 44 sec.   	|
|2 000 limit   	|749 830 144 bytes   	|  4 min. 38 sec.	|
|10 000 limit  	|754 323 456 bytes   	|  4 min. 31 sec. 	|
|20 000 limit  	|759 685 120 bytes   	|  4 min. 20 sec. 	|
|100 000 limit  	|800 952 320 bytes   	|  4 min. 22 sec. 	|
|200 000 limit  	|843 059 200 bytes   	|  4 min. 20 sec. 	|

Speed was not improved over 20 000 limit but memory consumption was higher. On my computer, 20 000 limit was making sense :)


**_It seems like you're keeping the id value, but then not using it for the parent value at all (that seems hard coded to 0)._**

Yes I forgot to talk about that... Does pstree is the only use for that value? Also, to get that value, we need to call the visit function, correct? I was thinking to remove the parent id value from the quicksqlite render. It will be the difference between quicksqlite and sqlite render. 

**_I can have a go at reworking this in a few days, or I'm happy for you to fix it up yourself?_**

I will push some code modification. No problem if you want to rework/add/modify it :)

**_Please ignore or delete the author line_**

Done :)

**Comment by iMHLv2** [comment]
Hey Sebastien - how are you? I'm just catching up on some issues for the 2.5 release. Are you happy with the current Quicksqlite renderer? Have you been using it since April without any major issues? 

Thanks!

**Comment by Sebastienbr** [comment]
I am fine thanks! Yes I am happy with the current Quicksqlite renderer: I am using it and found no issues with it. Thanks!

**Comment by iMHLv2** [comment]
OK....done! Thanks again! Let me know if you get a chance to test the current code base now. I tested the quicksqlite renderer with a few plugins and it seemed fine.

**Pull request closed without merging**
