### PR TITLE
AFF4 Support for Volatility

### PR DESCRIPTION
**Pull request by blschatz**
The first commit provides AFF4 support to volatility. 
The other commit (not really necessary) make a more efficient read when dealing with discontiguous address spaces.

### CODE REVIEW

**Comment by gleeda** [comment]
Thank you for the contribution!

While this could useful, I'd vote for moving it to the contrib folder, since we don't want to add dependencies.  This would be like how we keep the EWF address space.  I'll let the others weigh in in the meantime.

**Comment by blschatz** [comment]
Thanks. That sounds like a reasonable approach.

**Comment by jaredthecoder** [comment]
Has this been merged yet? We could really benefit from AFF4 compatibility for Volatility for the tools my team is building.

**Comment by jaredthecoder** [comment]
If not, I'd be willing to put in time to help make that happen.

**Comment by schatzforensic** [comment]
Thanks for the prod Jared. 
Gleeda, I have updated the patch to shift the AFF4 addressspace to contrib.

**Comment by gleeda** [comment]
@blschatz can you put `volatility/plugins/overlays/basic.py` back to the way it was prior for this pull request, or will this break something for the aff address space?  You can then issue a separate pull request for `volatility/plugins/overlays/basic.py` if those changes improve something.  Sorry to be a pain!

**Comment by schatzforensic** [comment]
No problem - it was an improvement that isn't necessary for the AFF4 support. Done.

**Comment by gleeda** [comment]
Thank you!  It's now merged :-)

**Pull request merged**
