### PR TITLE
Updated zeusscan to work with Volatility >= 2.3.1

### PR DESCRIPTION
**Pull request by Regala**
Tested with 2.3.1

### CODE REVIEW

**Comment by gleeda** [comment]
looks good and merged.  Thanks!

**Comment by gleeda** [comment]
Actually, this conflicts with the current code base so I'm going to revert this one.

**Comment by Regala** [comment]
Hum is there something I can do differently? Still a newbie on these pull
requests :)

2015-02-11 19:09 GMT+00:00 gleeda <notifications@github.com>:

**Comment by gleeda** [comment]
I'm actually curious what version of Volatility you are using in order
to have this work correctly.  Is it 2.3.1 or 2.4 or the current 2.5
codebase?

**Comment by Regala** [comment]
I tested it under 2.3.1

**Comment by gleeda** [comment]
ok, yeah, it was confusing from your title and your message.  That is
why we rejected it, because we are only interested in pull requests for
the current code base (2.5 and on). 

I apologize for my brief confusion, because I forgot that we merged
`procexedump` and `procmemdump` into one command with a `--memory` flag
to toggle between them.

**Comment by Regala** [comment]
Humm I see. Where's the 2.5 base though? I only see the 2.4 tag and below

2015-02-11 19:34 GMT+00:00 gleeda <notifications@github.com>:

**Comment by gleeda** [comment]
2.5 is in the current code base (it hasn't been released yet, but
contains code for that release).  The tag for 2.4 is only a moment in
time (a particular commit) in that code base.  So when you do a `git
pull` you are getting the code that will be in 2.5.

**Comment by Regala** [comment]
Got it. Anyway I tested the same plugin with the current code base and it
works. Apologies for the work :)

2015-02-11 19:54 GMT+00:00 gleeda <notifications@github.com>:

**Pull request merged**
